"""CONT-000 feasibility report (WP-1.5).

For each act: sample ``feasibility.levelsPerAct`` levels of ``spawner.wordsPerLevel`` words, and count
Babel candidate lines and counter-word traps under two pool scopes:

* ``level``: letters of this level's restored words only (Babel speaks from what you caught here);
* ``act``: letters restored so far in the act (cumulative), the O-13 fallback.

A level passes when it has at least ``babel.minCandidateLines`` lines and at least
``haz002.minCounterWords`` targets with a counter-word. The act passes when at least
``feasibility.passShare`` of its levels pass.
"""
from __future__ import annotations

import argparse
import random
import sys
import time
from collections import Counter

from astrolex_tools import load_tunables, reports_dir
from astrolex_tools.babel.compose import compose
from astrolex_tools.words.acts import ACT_FILES, load_acts
from astrolex_tools.words.blocklist import Blocklist
from astrolex_tools.words.db import WordDB, fits
from astrolex_tools.words.decoys import choose_decoys


def counter_words(target: str, pool_with_decoys: Counter, db: WordDB, bl: Blocklist, min_len: int, min_zipf: float = 0.0) -> list[str]:
    """Reasonably common dictionary words (not the target, not blocked) of length >= min_len formable from the target's letters plus decoys."""
    out = []
    for w, c in db.counters(8, True, min_zipf):
        if len(w) < min_len or w == target:
            continue
        if fits(c, pool_with_decoys):
            out.append(w)
    return out


def run(levels_per_act: int | None = None, seed: int | None = None) -> dict:
    t = load_tunables("spike")
    n_levels = levels_per_act or t["feasibility.levelsPerAct"]
    rng = random.Random(t["feasibility.seed"] if seed is None else seed)
    db, bl = WordDB.shared(), Blocklist.load()
    acts = load_acts()
    results = {}
    for act, words in acts.items():
        missing = [w for w in words if not db.is_word(w)]
        blocked = [w for w in words if bl.is_blocked(w)]
        levels = []
        act_pool = Counter()
        for i in range(n_levels):
            targets = rng.sample(words, t["spawner.wordsPerLevel"])
            level_pool = Counter("".join(targets))
            act_pool = act_pool + level_pool
            decoys, _ = choose_decoys(targets, t["spawner.decoysPerLevel"], rng, bl, t["blocklist.maxFormableLength"])
            screen_pool = level_pool + Counter(decoys)
            lines_level = compose(level_pool, targets)
            lines_act = compose(act_pool, targets) if i < 20 else None  # act scope saturates fast; sample the first 20
            cw = {tg: counter_words(tg, Counter(tg) + Counter(decoys), db, bl, t["haz002.counterWordMinLength"], t["haz002.counterWordZipfMin"]) for tg in targets}
            n_cw = sum(1 for v in cw.values() if v)
            levels.append({
                "targets": targets, "decoys": decoys,
                "lines_level": len(lines_level), "lines_act": None if lines_act is None else len(lines_act),
                "templates_level": sorted({ln.template_id for ln in lines_level}),
                "examples": [ln.text for ln in sorted(lines_level, key=lambda l: (-l.letters, l.text))[:4]],
                "signature": [ln.text for ln in lines_level if ln.template_id in ("signature", "not_that")][:3],
                "counter_words": {k: v[:3] for k, v in cw.items()}, "n_counter": n_cw,
                "pass": len(lines_level) >= t["babel.minCandidateLines"] and n_cw >= t["haz002.minCounterWords"],
            })
        passed = sum(1 for l in levels if l["pass"])
        act_scope_pass = sum(1 for l in levels if l["lines_act"] is not None and l["lines_act"] >= t["babel.minCandidateLines"] and l["n_counter"] >= t["haz002.minCounterWords"])
        act_scope_n = sum(1 for l in levels if l["lines_act"] is not None)
        results[act] = {
            "title": ACT_FILES[act], "words": len(words), "missing_from_db": missing, "blocked": blocked,
            "levels": levels, "pass_share": passed / n_levels,
            "act_scope_pass_share": act_scope_pass / act_scope_n if act_scope_n else None,
            "median_lines": sorted(l["lines_level"] for l in levels)[n_levels // 2],
            "share_with_signature": sum(1 for l in levels if l["signature"]) / n_levels,
            "share_with_counter": sum(1 for l in levels if l["n_counter"] >= 1) / n_levels,
        }
    return {"tunables": t, "acts": results}


def render(r: dict, elapsed: float) -> str:
    t = r["tunables"]
    out = ["# CONT-000 feasibility report: Babel's voice and counter-word traps (WP-1.5)\n",
           f"Generated by `python -m astrolex_tools.babel.feasibility` · seed {t['feasibility.seed']} · "
           f"{t['feasibility.levelsPerAct']} sampled levels per act · {t['spawner.wordsPerLevel']} words + {t['spawner.decoysPerLevel']} decoys per level · "
           f"pass = at least {t['babel.minCandidateLines']} candidate lines and {t['haz002.minCounterWords']} counter-word · "
           f"anagrams and counter-words must be reasonably common words (zipf >= {t['babel.anagramZipfMin']} / {t['haz002.counterWordZipfMin']}) · {elapsed:.0f}s\n",
           "## Summary\n",
           "| Act | Words | Levels passing (level scope) | Levels passing (act scope, first 20) | Median lines per level | Levels with a signature anagram line | Levels with a counter-word | Verdict |",
           "|---|---:|---:|---:|---:|---:|---:|---|"]
    overall = []
    for act, a in r["acts"].items():
        verdict = "PASS" if a["pass_share"] >= t["feasibility.passShare"] else "FAIL"
        overall.append(a["pass_share"])
        asp = "n/a" if a["act_scope_pass_share"] is None else f"{a['act_scope_pass_share']:.0%}"
        out.append(f"| {a['title']} | {a['words']} | {a['pass_share']:.0%} | {asp} | {a['median_lines']} | {a['share_with_signature']:.0%} | {a['share_with_counter']:.0%} | {verdict} |")
    mean = sum(overall) / len(overall)
    out.append("")
    if mean >= t["feasibility.passShare"]:
        rec = f"**O-13 recommendation: `level` scope.** {mean:.0%} of sampled levels carry Babel's voice from their own letters, above the {t['feasibility.passShare']:.0%} bar."
    else:
        rec = (f"**O-13 recommendation: `act` scope (or a richer template set).** Only {mean:.0%} of sampled levels carry at least "
               f"{t['babel.minCandidateLines']} lines from their own letters, below the {t['feasibility.passShare']:.0%} bar. See per-act detail for which templates carry the load.")
    out += [rec, ""]
    weak = [(a["title"], a["share_with_signature"]) for a in r["acts"].values() if a["share_with_signature"] < 0.5]
    if weak:
        out.append("**Note on the signature line.** The pure anagram rearrangement (SILENT -> LISTEN) is rarer than glue-word lines: "
                   + ", ".join(f"{title} {share:.0%}" for title, share in weak)
                   + " of levels have one. Options: choose act words with common anagram partners when the lists are revised, "
                     "or let only the `signature` template draw on letters restored earlier in the act. The other templates carry the voice on every level.")
        out.append("")
    out += ["## Data quality\n"]
    for act, a in r["acts"].items():
        if a["missing_from_db"] or a["blocked"]:
            out.append(f"- {a['title']}: not in DB {a['missing_from_db']}, blocked {a['blocked']}")
    if not any(a["missing_from_db"] or a["blocked"] for a in r["acts"].values()):
        out.append("- Every act word exists in the word database and none is blocked.")
    out.append("\n## Per-act detail (first 5 sampled levels)\n")
    for act, a in r["acts"].items():
        out.append(f"### {a['title']}\n")
        tpl_counts = Counter(tid for l in a["levels"] for tid in l["templates_level"])
        out.append("Templates that produced at least one line, by number of levels: " + ", ".join(f"`{k}` {v}" for k, v in tpl_counts.most_common()) + "\n")
        out.append("| Level words | Decoys | Lines | Counter-words | Example lines |")
        out.append("|---|---|---:|---|---|")
        for l in a["levels"][:5]:
            cw = "; ".join(f"{k}: {', '.join(v) if v else '–'}" for k, v in l["counter_words"].items())
            ex = "<br>".join(l["signature"][:2] + [e for e in l["examples"] if e not in l["signature"]][:2])
            out.append(f"| {' '.join(l['targets'])} | {''.join(l['decoys'])} | {l['lines_level']} | {cw} | {ex} |")
        out.append("")
    out += ["## How to read this\n",
            "- *Level scope* is the strict rule from Draft 3 §1.6: Babel uses only letters restored in this level. *Act scope* is the O-13 fallback.",
            "- Candidate counts are capped per template, so large numbers mean \"plenty\", not an exact total.",
            "- Lines are raw candidates. Wit is the owner's call: the point here is whether there is enough raw material to choose from.",
            "- Counter-words are reasonably common dictionary words formable from one target's letters plus the level's decoys; a trap is authored from one of them.",
            "- Obscure dictionary anagrams (SETON, BEGIRD, RYOTS) are excluded by the frequency floor so the counts reflect lines a player could actually read."]
    return "\n".join(out) + "\n"


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--levels", type=int, default=None, help="levels per act (default from tunables)")
    p.add_argument("--out", default="WP-1.5/feasibility.md", help="path under reports/")
    a = p.parse_args(argv)
    started = time.time()
    r = run(levels_per_act=a.levels)
    out = reports_dir() / a.out
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(r, time.time() - started))
    for act, res in r["acts"].items():
        print(f"{act}: level-scope pass {res['pass_share']:.0%}, median lines {res['median_lines']}, signature {res['share_with_signature']:.0%}, counter {res['share_with_counter']:.0%}")
    print("->", out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
