"""Babel's lexicon (WP-1.4): the words Babel is allowed to speak.

Built deterministically from the word database: common words (frequency floor), 2–8 letters,
with a WordNet part of speech, not blocked, plus the thematic list in ``data/babel/theme.txt``.
Written to ``data/babel/lexicon.txt`` (committed, ``status: draft`` until the owner approves).
"""
from __future__ import annotations

import sys
from collections import Counter
from dataclasses import dataclass
from functools import lru_cache

from astrolex_tools import data_dir
from astrolex_tools.words.blocklist import Blocklist
from astrolex_tools.words.db import WordDB

POS_MAP = {"n": "N", "v": "V", "a": "A", "s": "A", "r": "R"}
TARGET_SIZE = 500
ZIPF_FLOOR = 4.6
FUNCTION_WORDS = {  # glue Babel may use as {W}; tagged X (no content POS)
    "no", "not", "so", "or", "and", "if", "but", "yet", "then", "now", "still", "who", "what", "why", "how", "you", "me", "i",
    "we", "they", "it", "is", "are", "was", "be", "am", "do", "did", "can", "all", "none", "more", "less", "again", "never",
    "always", "here", "there", "too", "also", "only", "just", "yes",
}


@dataclass(frozen=True)
class LexWord:
    word: str
    pos: str  # N, V, A, R, X
    counter: Counter


def build_lexicon(target_size: int = TARGET_SIZE, zipf_floor: float = ZIPF_FLOOR) -> list[tuple[str, str]]:
    db = WordDB.shared()
    bl = Blocklist.load()
    theme = _read_theme()
    rows = db.con.execute(
        "SELECT word, pos, zipf FROM words WHERE blocked=0 AND length BETWEEN 2 AND 8 AND in_wordnet=1 AND zipf>=? ORDER BY zipf DESC",
        (zipf_floor,),
    ).fetchall()
    out: dict[str, str] = {}
    for w in theme:
        r = db.row(w)
        if r is None or bl.is_blocked(w):
            print(f"theme word not in DB or blocked: {w}", file=sys.stderr)
            continue
        out[w] = POS_MAP.get(r["pos"] or "", "N")
    for w in sorted(FUNCTION_WORDS):
        if not bl.is_blocked(w):
            out.setdefault(w, "X")
    for r in rows:
        if len(out) >= target_size:
            break
        out.setdefault(r["word"], POS_MAP.get(r["pos"], "N"))
    return sorted(out.items())


def _read_theme() -> list[str]:
    path = data_dir() / "babel" / "theme.txt"
    return [ln.split("#", 1)[0].strip().lower() for ln in path.read_text().splitlines() if ln.split("#", 1)[0].strip()]


def write_lexicon() -> None:
    lex = build_lexicon()
    path = data_dir() / "babel" / "lexicon.txt"
    header = (
        "# Babel's lexicon: word<TAB>pos (N noun, V verb, A adjective, R adverb, X function word).\n"
        f"# Generated by `python -m astrolex_tools.babel.lexicon` from the word DB (zipf >= {ZIPF_FLOOR}, WordNet sense, not blocked)\n"
        "# plus data/babel/theme.txt. Edit theme.txt or the generator, not this file. status: draft\n"
    )
    path.write_text(header + "".join(f"{w}\t{p}\n" for w, p in lex))
    print(f"wrote {len(lex)} words to {path}", file=sys.stderr)


@lru_cache(maxsize=1)
def load_lexicon() -> list[LexWord]:
    path = data_dir() / "babel" / "lexicon.txt"
    out = []
    for line in path.read_text().splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        w, pos = line.split("\t")
        out.append(LexWord(w, pos, Counter(w)))
    return out


if __name__ == "__main__":
    write_lexicon()
