"""Export the data the Phase 2 browser toy needs (WP-2.1/2.3) to ``web/toy/data.js``.

The toy is a static page with no fetch access, so everything ships as one script that sets
``window.ASTROLEX_DATA``: act word lists, Babel lexicon and templates, and precomputed
common anagrams for every act word (so the JS composer never needs the dictionary).
Regenerate with ``python -m astrolex_tools.export_toy_data``.
"""
from __future__ import annotations

import json
import sys

from astrolex_tools import load_tunables, repo_root
from astrolex_tools.babel.compose import anagrams_of, load_templates
from astrolex_tools.babel.lexicon import load_lexicon
from astrolex_tools.words.acts import ACT_FILES, load_acts


def main() -> int:
    t = load_tunables("spike")
    acts = load_acts()
    theme = [ln.split("#", 1)[0].strip().lower() for ln in (repo_root() / "data" / "babel" / "theme.txt").read_text().splitlines() if ln.split("#", 1)[0].strip()]
    data = {
        "acts": {k: {"title": ACT_FILES[k], "words": v} for k, v in acts.items()},
        "lexicon": [[lw.word, lw.pos] for lw in load_lexicon()],
        "theme": theme,
        "templates": [{"id": tp.id, "pattern": tp.pattern} for tp in load_templates()],
        "anagrams": {w: anagrams_of(w) for words in acts.values() for w in words},
        "tunables": {
            "tether.travelTime": 0.2, "tether.hitTolerance": 0.35, "tap.radiusPx": 28, "tap.radiusDriftMul": 1.25,
            "drift.speed": 0.55, "drift.spin": 0.6, "spawner.decoys": 4, "spawner.wordsPerLevel": t["spawner.wordsPerLevel"],
            "oxygen.max": 100, "oxygen.drainPerSec": 1.0, "oxygen.wrongCost": 4, "oxygen.restoreBase": 12, "oxygen.restorePerLetter": 2,
            "score.letterValue": 10, "score.lengthStep": 0.1, "combo.step": 0.1, "combo.max": 2.0, "score.oxygenBonus": 2,
            "babel.showSeconds": 2.6, "babel.minLineLetters": t["babel.minLineLetters"],
        },
    }
    out = repo_root() / "web" / "toy" / "data.js"
    out.write_text("// Generated by `python -m astrolex_tools.export_toy_data`. Do not edit by hand.\nwindow.ASTROLEX_DATA = " + json.dumps(data, separators=(",", ":")) + ";\n")
    print(f"wrote {out} ({out.stat().st_size // 1024} KB): {sum(len(v) for v in acts.values())} act words, {len(data['lexicon'])} lexicon words, {sum(1 for v in data['anagrams'].values() if v)} words with anagrams", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
